## [处理 Go 中的错误](https://www.digitalocean.com/community/tutorials/handling-errors-in-go)

由 **Gopher Guides** 编写，[@JialeDai](https://github.com/daijiale) 译

>健壮的代码往往需要能应对更多意外的异常场景。例如，用户输入异常、网络连接异常、磁盘故障等。错误处理是能自动识别程序何时何地处于何种异常状态，并根据状态分批记录诊断信息，供之后调试的过程。与那些需要研发人员使用特殊语法糖来处理异常信息的语言不同，Go中的异常错误信息是通过从函数返回的`error`类型来定义区分，处理逻辑与其他类型的函数返回值一样。要处理Go中的异常错误，我们必须提前定义函数可以返回这些异常错误类型来确定程序是否在执行过程中抛出了异常，同时，采取适当的措施来保护程序数据并通知用户/操作员这个异常事件已发生。

### 创建错误

在我们处理错误信息之前，我们需要先创建一些。Go标准库提供了两个内置函数来创建错误信息：`errors.New` 和 `fmt.Errorf`。这两个方法都允许你自定义面向用户侧所展示的错误信息。 `errors.New` 只接受一个传入参数：字符串类型的错误信息。你可以通过自定义这个参数来提示用户这个错误的具体内容。我们尝试通过运行下文的例子来看一看一个由`errors.New` 所产生的错误信息：

```go
package main

import ( 
    "errors"
    "fmt"
)

func main() {
    err := errors.New("barnacles") 
    fmt.Println("Sammy says:", err)
}
```

输出为：

```
Sammy says: barnacles
```


我们使用标准库中的 `errors.New` 方法来创建新的错误，并以字符串类型的'barnacles'作为错误内容的描述。依照[Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)标准，我们常常使用小写字母来命名错误内容描述。

最终，我们使用`fmt.Println`方法来组合 'Sammy says: '信息，并打印出来。

使用 `fmt.Errorf`方法可以动态的生成错误信息。它的第一个传参是可带占位符的动态变量：`%s`标识字符串，`%d`标识整数。 `fmt.Errorf`将该格式字符串后面的参数按顺序插入到这些占位符变量之中：

```go
package main

import (
    "fmt"
    "time"
)

func main() {
    err := fmt.Errorf("error occurred at: %v", time.Now())
    fmt.Println("An error happened:", err)
}

```

输出为：

```
An error happened: Error occurred at: 2019-07-11 16:52:42.532621 -0400 EDT m=+0.000137103
```

我们使用了`fmt.Errorf`方法来构建一条包含当前时间的错误信息。我们在`fmt.Errorf`所传字符串参数中指定了 `%v`占位符变量来承接标准库中`time.Now`函数返回的当前时间实际值。与前面的示例类似，我们将错误内容与一个错误前缀组合在一起，并使用`fmt.Println`打印而出。


### 处理错误

通常，我们不会看到如上例所示处理错误的场景。更多时候，我们是在出现异常问题时，创建一个错误并通过函数返回，然后函数调用方可以通过`if`语句和错误返回值是否为`nil`来进行异常下游逻辑处理。

下一个示例包含一个始终返回错误的函数。值得注意的是，当你运行该程序时，即使这次的错误类型是以函数方式返回，它依然会产生与上个示例相同的输出。用不同的方式去声明引用错误类型，并不会错误的内容描述。


```go
package main

import (
    "errors"
    "fmt"
)

func boom() error {
    return errors.New("barnacles")
}

func main() {
    err := boom()

    if err != nil {
        fmt.Println("An error occurred:", err)
        return
    }
    fmt.Println("Anchors away!")
}

```

输出为：

```
An error occurred: barnacles
```

这里，我们定义了一个名为`boom()`的函数，该函数返回一个使用`error.New`构造的错误实例。之后，我们调用此函数并使用`err:=boom()`捕获错误实例。

一旦我们获取到了这个错误实例，我们就可以使用`if err != nil`条件来判断错误是否存在。在例子中，这里的条件校验将始终为true，因为`boom()`必然会返回一个错误实例，但是在我们实际的工作中，情况却并非往往都是如此，因此最好的做法是进行多段逻辑处理以解决错误不存在（`nil`）和错误存在的情况。当错误存在时，像之前的示例中一样，我们使用`fmt.Println`来打印错误或带有前缀的错误讯息。最后，我们使用`return`语句跳过`fmt.Println("Anchors away!")`的执行就返回，因为这句仅在错误不存在时才执行。


>注意：最后一个示例中所使用的`if err != nil`编写方式，常在Go语言中被用来处理错误。只要某个函数返回可能产生错误，那么使用if语句检查错误是否存在就非常有必要。在Go语言编码规范中，if条件判断后的第一层缩进块常用来承接[`“happy path”`](https://en.wikipedia.org/wiki/Happy_path)逻辑，第二层级缩进块用来承接所有的[`“sad path”`](https://en.wikipedia.org/wiki/Happy_path)逻辑。


`if`语句具有可选的复合语法，可用于帮助简化调用函数和处理错误的程式。

我们来运行一个和之前示例同样输出的程序，但是这次使用`if复合语法来减少一些


```go
package main

import (
    "errors"
    "fmt"
)

func boom() error {
    return errors.New("barnacles")
}

func main() {
    if err := boom(); err != nil {
        fmt.Println("An error occurred:", err)
        return
    }
    fmt.Println("Anchors away!")
}

```

输出为：

```
An error occurred: barnacles
```

和之前的例子一样，我们构造了一个`boom()`函数，该函数会始终返回一个错误实例。在`if`条件语句的第一部分，我们将`boom()`函数中返回的错误分配给了`err`，在分号后`if`的第二部分处，`err`被赋值了。之后，根据`err`是否存在来决定是否打印出这个错误信息。

本节，我们学会了如何处理只返回一个错误值的函数。这些函数是触类旁通的，对于后面我们学习处理多类返回值的函数也是有借鉴意义的。


### 同时返回错误和值

只返回一个错误值的函数通常是那些会引起状态变化的函数，例如：向数据库中插入一行数据。通常我们在实际工作中会编写一些不仅在执行成功时返回指定值，同时在执行失败后返回一个潜在错误的函数。Go语言也支持函数返回多个结果，这些结果中往往也会同时返回一个指定值和一个错误类型。

为了创建一个同时返回多个值的函数，我们在函数签名中的括号内列出了每个返回值的类型。例如：`capitalize`函数使用`func capitalize(name string) (string, error) {}`定义此函数将要返回了一个字符串类型和一个错误类型。`

运行下方程序，查看输出的字符串类型和错误类型结果：


```go
package main

import (
    "errors"
    "fmt"
    "strings"
)

func capitalize(name string) (string, error) {
    if name == "" {
        return "", errors.New("no name provided")
    }
    return strings.ToTitle(name), nil
}

func main() {
    name, err := capitalize("sammy")
    if err != nil {
        fmt.Println("Could not capitalize:", err)
        return
    }

    fmt.Println("Capitalized name:", name)
}

```

输出为：

```
Capitalized name: SAMMY
```

我们将`capitalize() `定义为一个接受字符串传入并返回字符串类型和错误类型的函数。在`main()`函数中，我们调用`capitalize() `并将函数返回的两个值分配给`name`和`err`变量。此后，像之前例子中一样，使用`if err != ni`检查异常，如果存在错误，则通过`fmt.Println`打印。如果没有错误，则打印`SAMMY`。

尝试将`name, err := capitalize("sammy")`中的字符串传参`sammy`变为空字符串`("")`，之后，程序会输出错误信息：`Could not capitalize: no name provided`。

`capitalize()`函数如果接收的是一个空字符串传参，将会返回一个错误。当`name`参数非空时，`capitalize()`使用`strings.ToTitle`将`name`传参变为大写并返回错误值为`nil`。

这个示例中有一些特殊约定，这些约定是Go语言的编码规范，但尚未由Go编译器强制约束。当函数返回多个值（包含错误类型）时，约定要求我们将错误作为最后一项返回。具有多个返回值的函数返回错误时，Go语言编码一惯会将每个非错误值设置为零值。零值，泛指：空字符串，整形0，空结构体、nil接口、空指针等。在[变量和常量](https://www.digitalocean.com/community/tutorials/how-to-use-variables-and-constants-in-go#zero-values)的教程中，我们将更详细地介绍零值的意义。


#### 减少冗余代码

遵循Go语言的编码规范，在函数返回多值的情况下有时会使得程序非常不优雅。我们可以使用[匿名函数](https://en.wikipedia.org/wiki/Anonymous_function)来帮助减少冗余代码。

匿名函数职责是为了组装变量。与我们之前示例中所定义的函数不同，它们仅仅在声明它们的函数中才可使用，这使得它们非常适合用做小而美的可复用的辅助逻辑模块。

下例程序修改了上一个我们大写字符转换的程序示例。由于它具有三个要返回的值，如果没有匿名函数来协助我们，处理错误将变得很麻烦：

```go
package main

import (
    "errors"
    "fmt"
    "strings"
)

func capitalize(name string) (string, int, error) {
    handle := func(err error) (string, int, error) {
        return "", 0, err
    }

    if name == "" {
        return handle(errors.New("no name provided"))
    }

    return strings.ToTitle(name), len(name), nil
}

func main() {
    name, size, err := capitalize("sammy")
    if err != nil {
        fmt.Println("An error occurred:", err)
    }

    fmt.Printf("Capitalized name: %s, length: %d", name, size)
}

```
输出为：

```
Capitalized name: SAMMY, length: 5
```


在`main()`函数中，我们分别获取到了`name`，`size`，`err`这三个来自`capitalize`中的返回值。之后，我们通过判断`err`变量是否等于`nil`来判断`capitalize`函数是否异常。在尝试使用`capitalize`返回的其他值之前，务必要执行此操作，因为匿名函数`handle`可以把这些变量都设置为零值。如果没有异常错误产生，我们就会把`sammy`大写输出并打印其字符串长度。

另外，可以将传入参数由`sammy`改为空字符串，你将看到如下错误信息：

```
An error occurred: no name provided
```

在`capitalize`函数中，我们将`handle`变量定义为匿名函数。它与`capitalize`函数中的返回值定义一样。`handle`将这些值设置为零值，并将错误传参类型透传为最终函数返回值。使用此方法，我们可以通过使用匿名函数中的`return`语句来处理异常错误，并透传进`capitalize`函数中。

请记住，由于我们函数定义的缘故，`capitalize`函数必须始终返回三个值。有时候我们不需要返回所有定义的值，很幸运，我们都可以通过`handle`匿名函数来灵活分配设置。

### 处理来自多种返回值函数的错误

当一个函数返回多个变量值，Go语言要求我们为每一个变量分配一个值。在上一个示例中，我们通过提前为`capitalize`函数定义形参来实现此目的，这些形参应以逗号分隔，并在`:=`运算符左侧被赋值。`capitalize`函数的第一个返回值被分配给了`name`，第二个返回值被分配给了`err`。如果我们只对错误`err`感兴趣，我们可以把不想要的变量返回值用特殊变量符`_`代替。

在下例程序中，我们修改了第一个`capitalize`示例，通过传入空字符串来产生错误。尝试运行该程序，看我们如何通过使用`_`变量来舍弃第一个返回值，仅检查错误返回信息。

```go
package main

import (
    "errors"
    "fmt"
    "strings"
)

func capitalize(name string) (string, error) {
    if name == "" {
        return "", errors.New("no name provided")
    }
    return strings.ToTitle(name), nil
}

func main() {
    _, err := capitalize("")
    if err != nil {
        fmt.Println("Could not capitalize:", err)
        return
    }
    fmt.Println("Success!")
}

```
输出为：

```
Could not capitalize: no name provided
```

这次在`main()`函数中，我们分配下划线变量`_`给到`capitalized`函数的`string`类型返回值。同时，我们分配
`capitalized`函数的`error`类型给`err`变量。之后，我们通过`if err != nil`来判断当前错误是否存在。` _, err := capitalize("")`语句将会指定传参为空字符串而使得后续执行条件始终为`true`，程序将在`if`条件为真下打印出`"Could not capitalize: no name provided"`信息。函数会跳过`fmt.Println("Success!")`，直接返回。

### 小结

本节我们已经了解了很多使用标准库创建错误的方式，以及如何构建常用的错误返回函数。在本教程中，我们已经成功使用标准库的错误处理方法（`errors.New`和 `fmt.Errorf`）。下一节中，我们将研究如何创建自定义（非标准库定义的）的错误类型，以向用户传递更丰富的错误信息。